import { cities } from 'src/app/lib/inteerfaces/cities';

 const datasort:cities[] =[
  {
    "city": "Amman", 
    "lat": "31.9500", 
    "lng": "35.9333", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Asimah", 
    "capital": "primary", 
    "population": "4007526", 
    "population_proper": "4007526"
  }, 
  {
    "city": "Irbid", 
    "lat": "32.5556", 
    "lng": "35.8500", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Irbid", 
    "capital": "admin", 
    "population": "1088100", 
    "population_proper": "1088100"
  }, 
  {
    "city": "Az ZarqA", 
    "lat": "32.0833", 
    "lng": "36.1000", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Az ZarqA", 
    "capital": "admin", 
    "population": "481300", 
    "population_proper": "481300"
  }, 
  {
    "city": "Al Aqabah", 
    "lat": "29.5167", 
    "lng": "35.0000", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Aqabah", 
    "capital": "admin", 
    "population": "140000", 
    "population_proper": "140000"
  }, 
  {
    "city": "As Salt", 
    "lat": "32.0333", 
    "lng": "35.7333", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al BalqA", 
    "capital": "admin", 
    "population": "88900", 
    "population_proper": "88900"
  }, 
  {
    "city": "Al Mafraq", 
    "lat": "32.2833", 
    "lng": "36.2333", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Mafraq", 
    "capital": "admin", 
    "population": "57118", 
    "population_proper": "57118"
  }, 
  {
    "city": "Jarash", 
    "lat": "32.2723", 
    "lng": "35.8914", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Jarash", 
    "capital": "admin", 
    "population": "50745", 
    "population_proper": "50745"
  }, 
  {
    "city": "MaAn", 
    "lat": "30.1920", 
    "lng": "35.7360", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "MaAn", 
    "capital": "admin", 
    "population": "50350", 
    "population_proper": "50350"
  }, 
  {
    "city": "At turrah", 
    "lat": "32.6368", 
    "lng": "35.9900", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Irbid", 
    "capital": "", 
    "population": "34948", 
    "population_proper": "34948"
  }, 
  {
    "city": "At tafilah", 
    "lat": "30.8375", 
    "lng": "35.6042", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "At tafilah", 
    "capital": "admin", 
    "population": "25429", 
    "population_proper": "25429"
  }, 
  {
    "city": "Al Karak", 
    "lat": "31.1833", 
    "lng": "35.7000", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Karak", 
    "capital": "admin", 
    "population": "21678", 
    "population_proper": "21678"
  }, 
  {
    "city": "Al Abdalli", 
    "lat": "31.9650", 
    "lng": "35.9082", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Asimah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Ar Rusayfah", 
    "lat": "32.0178", 
    "lng": "36.0464", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Az ZarqA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "MArkA", 
    "lat": "31.9863", 
    "lng": "35.9965", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Asimah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al Jubayhah", 
    "lat": "32.0256", 
    "lng": "35.8644", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Asimah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al Juwayyidah", 
    "lat": "31.9167", 
    "lng": "35.9500", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Asimah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "MAdabA", 
    "lat": "31.7167", 
    "lng": "35.8000", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "MadabA", 
    "capital": "admin", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Ajlun", 
    "lat": "32.3325", 
    "lng": "35.7517", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Ajlun", 
    "capital": "admin", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Ayn al BAshA", 
    "lat": "32.0573", 
    "lng": "35.8311", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al BalqA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "WAdi as Sir", 
    "lat": "31.9545", 
    "lng": "35.8183", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Asimah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al Fuhays", 
    "lat": "32.0047", 
    "lng": "35.7809", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al BalqA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al MazAr ash ShamAli", 
    "lat": "32.4704", 
    "lng": "35.7969", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Irbid", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Kafr Asad", 
    "lat": "32.5980", 
    "lng": "35.7127", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Irbid", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al hisn", 
    "lat": "32.4845", 
    "lng": "35.8841", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Irbid", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Dayr Abu Said", 
    "lat": "32.4982", 
    "lng": "35.6867", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Irbid", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "At tayyibah", 
    "lat": "32.5430", 
    "lng": "35.7176", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Irbid", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Ash Shunah ash ShamAliyah", 
    "lat": "32.6100", 
    "lng": "35.6080", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Irbid", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "NAur", 
    "lat": "31.8744", 
    "lng": "35.8247", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Asimah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "IrjAn", 
    "lat": "32.3945", 
    "lng": "35.7334", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Ajlun", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Ar RamthA", 
    "lat": "32.5592", 
    "lng": "36.0069", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Irbid", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Muthallath JAmiat Al al Bayt", 
    "lat": "32.3459", 
    "lng": "36.2335", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Mafraq", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Kufrinjah", 
    "lat": "32.3000", 
    "lng": "35.7000", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Ajlun", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al HAshimiyah", 
    "lat": "32.1333", 
    "lng": "36.1167", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Az ZarqA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "SammA ar RawsAn", 
    "lat": "32.6379", 
    "lng": "35.8266", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Irbid", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "sakhrah", 
    "lat": "32.3709", 
    "lng": "35.8427", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Ajlun", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al Mastabah", 
    "lat": "32.1843", 
    "lng": "35.8559", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Jarash", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Juraynah", 
    "lat": "31.7667", 
    "lng": "35.8000", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "MadabA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Manshiyat Bani hasan", 
    "lat": "32.3707", 
    "lng": "36.0793", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Mafraq", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "hisbAn", 
    "lat": "31.7982", 
    "lng": "35.8099", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Asimah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "AllAn", 
    "lat": "32.1182", 
    "lng": "35.7435", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al BalqA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Umm al BasAtin", 
    "lat": "31.8245", 
    "lng": "35.8779", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Asimah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Dayr AllA", 
    "lat": "32.1889", 
    "lng": "35.6031", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al BalqA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al KhAlidiyah", 
    "lat": "32.1790", 
    "lng": "36.3033", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Mafraq", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Ayy", 
    "lat": "31.1337", 
    "lng": "35.6437", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Karak", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "SamA as SirhAn", 
    "lat": "32.4686", 
    "lng": "36.2436", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Mafraq", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Az̧ Z̧ulayl", 
    "lat": "32.1208", 
    "lng": "36.2801", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Az ZarqA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Ash Shunah al Janubiyah", 
    "lat": "31.8915", 
    "lng": "35.6178", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al BalqA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al MazAr al Janubi", 
    "lat": "31.0672", 
    "lng": "35.6949", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Karak", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Umm al JimAl", 
    "lat": "32.3286", 
    "lng": "36.3679", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Mafraq", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al husayniyah", 
    "lat": "31.0261", 
    "lng": "35.7229", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Karak", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "BalamA", 
    "lat": "32.2365", 
    "lng": "36.0881", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Mafraq", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Mulayh", 
    "lat": "31.5881", 
    "lng": "35.8125", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "MadabA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Fuqu", 
    "lat": "31.3681", 
    "lng": "35.7022", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Karak", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "IrhAb", 
    "lat": "32.3234", 
    "lng": "36.0909", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Mafraq", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "BurmA", 
    "lat": "32.2193", 
    "lng": "35.7851", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Jarash", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "As subayhi", 
    "lat": "32.1484", 
    "lng": "35.7053", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al BalqA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "hawshA", 
    "lat": "32.4514", 
    "lng": "36.0990", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Mafraq", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "SahAb", 
    "lat": "31.8703", 
    "lng": "36.0048", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Asimah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "WAdi Musá", 
    "lat": "30.3289", 
    "lng": "35.4403", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "MaAn", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al Faysaliyah", 
    "lat": "31.7491", 
    "lng": "35.7692", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "MadabA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al Qasr", 
    "lat": "31.3141", 
    "lng": "35.7439", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Karak", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Umm al Qittayn", 
    "lat": "32.3145", 
    "lng": "36.6283", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Mafraq", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "YarqA", 
    "lat": "31.9758", 
    "lng": "35.6964", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al BalqA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Birayn", 
    "lat": "32.0994", 
    "lng": "35.9578", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Az ZarqA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "BusayrA", 
    "lat": "30.7326", 
    "lng": "35.6094", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "At tafilah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al Mughayyir", 
    "lat": "31.4063", 
    "lng": "35.7708", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Karak", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Ghawr as sAfi", 
    "lat": "31.0369", 
    "lng": "35.4877", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Karak", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Rujm ash ShAmi al Gharbi", 
    "lat": "31.8333", 
    "lng": "36.0167", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Asimah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "sabhA", 
    "lat": "32.3270", 
    "lng": "36.5016", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Mafraq", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "DhibAn", 
    "lat": "31.4989", 
    "lng": "35.7829", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "MadabA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "MAin", 
    "lat": "31.6800", 
    "lng": "35.7320", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "MadabA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Ayl", 
    "lat": "30.2059", 
    "lng": "35.5363", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "MaAn", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al Muwaqqar", 
    "lat": "31.8147", 
    "lng": "36.1088", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Asimah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Ghawr al Mazraah", 
    "lat": "31.2659", 
    "lng": "35.5167", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Karak", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Ash Shawbak", 
    "lat": "30.5213", 
    "lng": "35.5714", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "MaAn", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Dayr al Kahf", 
    "lat": "32.2753", 
    "lng": "36.8395", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Mafraq", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al Ariḑ", 
    "lat": "31.5584", 
    "lng": "35.6574", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "MadabA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Adhruh", 
    "lat": "30.3281", 
    "lng": "35.5986", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "MaAn", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Muthallath sabhA", 
    "lat": "32.2601", 
    "lng": "36.4678", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Mafraq", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al husayniyah", 
    "lat": "30.5955", 
    "lng": "35.7970", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "MaAn", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al Jizah", 
    "lat": "31.6989", 
    "lng": "35.9553", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Asimah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al hasA", 
    "lat": "30.8213", 
    "lng": "35.9750", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "At tafilah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al Murayghah", 
    "lat": "30.0953", 
    "lng": "35.5231", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "MaAn", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al Quwayrah", 
    "lat": "29.8047", 
    "lng": "35.3111", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Aqabah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Ad Disah", 
    "lat": "29.6528", 
    "lng": "35.5112", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Aqabah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al QatrAnah", 
    "lat": "31.2508", 
    "lng": "36.0493", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Karak", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Umm ar RasAs", 
    "lat": "31.5122", 
    "lng": "35.9184", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Asimah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Muthallath al Azraq", 
    "lat": "31.8327", 
    "lng": "36.8149", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Az ZarqA", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Ar Rishah", 
    "lat": "30.2243", 
    "lng": "35.2167", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Aqabah", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Ar Ruwayshid", 
    "lat": "32.5015", 
    "lng": "38.2040", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "Al Mafraq", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }, 
  {
    "city": "Al Jafr", 
    "lat": "30.3184", 
    "lng": "36.1777", 
    "country": "Jordan", 
    "iso2": "JO", 
    "admin_name": "MaAn", 
    "capital": "minor", 
    "population": "", 
    "population_proper": ""
  }
]

export const data =  datasort.sort(function(a, b){
    if(a.city < b.city) { return -1; }
    if(a.city > b.city) { return 1; }
    return 0;
});